spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: your-connection-url
    username: your-username
    password: your-password
  # redis
  data:
    redis:
      host: your-connection-url
      port: 6379
      database: 0
      password: your-password
      ttl: 3600
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: your-api-key
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: false
      log-responses: false
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: your-api-key
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: false
      log-responses: false
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: your-api-key
      model-name: deepseek-chat
      max-tokens: 8192
      temperature: 0.1
      log-requests: false
      log-responses: false
    # 智能路由 AI 模型配置
    route-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: your-api-key
      model-name: qwen-flash
      max-tokens: 100
      log-requests: false
      log-responses: false

jetcache:
  areaInCacheName: false
  statIntervalMinutes: 15
  local:
    default:
      type: caffeine
      limit: 100
      expireAfterWriteInMillis: 3600000
  remote:
    default:
      type: redis
      host: your-ip
      port: your-port
      password: your-password
      cacheNullValue: true
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
        maxWaitMillis: 10000

# 添加 COS 对象存储配置（需要从腾讯云获取）
tencent:
  cos:
    host: your-cos-host
    secret-id: your-secret-id
    secret-key: your-secret-key
    bucket: your-bucket
    region: your-region

# 生产环境关闭日志
mybatis-flex:
  configuration:
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
# 部署路径
code:
  deploy-host: your-deploy-path

# 热 key 探测
hotkey:
  app-name: ai_code_generator
  #本地缓存大小限制
  caffeine-size: 10000
  #推送频率,客户端累加，达到指定时间后推送给worker
  push-period: 1000
  etcd-server: your-etcd-url
